package com.oneau.loader.ephemeris;

import static com.oneau.loader.ephemeris.SchemaObjectDefinition.*;
import static java.lang.String.format;
import static java.util.Arrays.asList;
import static java.util.Collections.unmodifiableList;

import java.util.List;

public class HsqlGenerator extends AbstractSqlGenerator {

    /* (non-Javadoc)
	 * @see com.oneau.loader.ephemeris.SqlGenerator#generateSchema()
	 */
    @Override
	public List<String> generateSchema() {
        return unmodifiableList(
                asList(
                       format("CREATE SCHEMA %s AUTHORIZATION DBA%s", SCHEMANAME, eol()),
                       format("CREATE MEMORY TABLE %s.%s(ID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(64) NOT NULL,FILENAME VARCHAR(64) NOT NULL,KSIZE INTEGER NOT NULL,NUM_COEFF INTEGER NOT NULL,EPOCH_START NUMERIC NOT NULL,EPOCH_END NUMERIC NOT NULL,CONSTRAINT SYS_CT_46 UNIQUE(NAME),CONSTRAINT SYS_CT_47 UNIQUE(FILENAME)) %s", SCHEMANAME, EPHEMERIS_HEADER, eol()),
                       format("CREATE MEMORY TABLE %s.%s(ID INTEGER NOT NULL PRIMARY KEY,FILENAME VARCHAR(64) NOT NULL,HEADER_ID INTEGER NOT NULL,CONSTRAINT SYS_CT_52 UNIQUE(HEADER_ID,FILENAME),CONSTRAINT SYS_FK_53 FOREIGN KEY(HEADER_ID) REFERENCES EPHEMERIS_HEADER(ID)) %s", SCHEMANAME, EPHEMERIS_DATA, eol()),
                       format("CREATE MEMORY TABLE %s.%s(ID INTEGER NOT NULL PRIMARY KEY,RANGE_FROM NUMERIC NOT NULL,RANGE_TO NUMERIC NOT NULL,CONSTRAINT SYS_CT_59 UNIQUE(RANGE_FROM,RANGE_TO)) %s", SCHEMANAME, EPHEMERIS_INTERVAL, eol()),
                       format("CREATE MEMORY TABLE %s.%s(ID INTEGER NOT NULL PRIMARY KEY,NAME VARCHAR(64) NOT NULL,DIMENSIONS INTEGER NOT NULL,CHEB_COEFFS INTEGER NOT NULL,COEFF_SETS INTEGER NOT NULL,CONSTRAINT SYS_CT_63 UNIQUE(NAME)) %s", SCHEMANAME, MEASURED_ITEM, eol()),
                       format("CREATE MEMORY TABLE %s.%s(ID INTEGER NOT NULL PRIMARY KEY,HEADER_ID INTEGER NOT NULL,NAME VARCHAR(64) NOT NULL,VALUE VARCHAR(64) NOT NULL,CONSTRAINT SYS_FK_67 FOREIGN KEY(HEADER_ID) REFERENCES EPHEMERIS_HEADER(ID),CONSTRAINT SYS_CT_68 UNIQUE(HEADER_ID,NAME))%s", SCHEMANAME, CONSTANT, eol()),
                       format("CREATE CACHED TABLE %s.%s(ID INTEGER NOT NULL PRIMARY KEY,FILE_ID INTEGER NOT NULL,MEASURED_ITEM_ID INTEGER NOT NULL,OBSERVATION_NUM INTEGER NOT NULL,INTERVAL_ID INTEGER,COEFFICIENT NUMERIC NOT NULL,CONSTRAINT SYS_FK_74 FOREIGN KEY(FILE_ID) REFERENCES EPHEMERIS_DATA(ID),CONSTRAINT SYS_FK_75 FOREIGN KEY(MEASURED_ITEM_ID) REFERENCES MEASURED_ITEM(ID),CONSTRAINT SYS_FK_76 FOREIGN KEY(INTERVAL_ID) REFERENCES EPHEMERIS_INTERVAL(ID)) %s", SCHEMANAME, OBSERVATION, eol()),
                       format("SET TABLE %s.%s INDEX'56621544 56621544 32 56621544 0' %s", SCHEMANAME, OBSERVATION, eol()),
                       format("CREATE USER %s PASSWORD '%s' %s", SCHEMANAME, pwd(), eol()),
                       format("SET WRITE_DELAY 10%s", eol()),
                       format("SET SCHEMA %s %s", SCHEMANAME, eol())
                )
        );
    }
    

	@Override
	protected String eol() {
		return "\n";
	}

}
