CREATE SCHEMA ONEAU AUTHORIZATION DBA
CREATE USER ONEAU PASSWORD ONEAU
CREATE MEMORY TABLE ONEAU.EPHEMERIS_HEADER (id INTEGER PRIMARY KEY, NAME VARCHAR(64) NOT NULL, FILENAME VARCHAR(64) NOT NULL, KSIZE INTEGER NOT NULL, NUM_COEFF INTEGER NOT NULL, EPOCH_START NUMERIC NOT NULL, EPOCH_END NUMERIC NOT NULL, UNIQUE(NAME), UNIQUE(FILENAME))
CREATE MEMORY TABLE ONEAU.EPHEMERIS_DATA (id INTEGER PRIMARY KEY, FILENAME VARCHAR(64) NOT NULL, HEADER_ID INTEGER NOT NULL, UNIQUE(HEADER_ID,FILENAME), FOREIGN KEY(HEADER_ID) REFERENCES ONEAU.EPHEMERIS_HEADER (id) )
CREATE MEMORY TABLE ONEAU.EPHEMERIS_INTERVAL (id INTEGER PRIMARY KEY, RANGE_FROM NUMERIC NOT NULL, RANGE_TO NUMERIC NOT NULL, UNIQUE(RANGE_FROM, RANGE_TO))
CREATE MEMORY TABLE ONEAU.MEASURED_ITEM (id INTEGER PRIMARY KEY, NAME VARCHAR(64) NOT NULL, DIMENSIONS INTEGER NOT NULL, CHEB_COEFFS INTEGER NOT NULL, COEFF_SETS INTEGER NOT NULL, UNIQUE(NAME))
CREATE MEMORY TABLE ONEAU.CONSTANT(id INTEGER PRIMARY KEY, HEADER_ID INTEGER NOT NULL ,NAME VARCHAR(64) NOT NULL,VALUE VARCHAR(64) NOT NULL, FOREIGN KEY (HEADER_ID) REFERENCES ONEAU.EPHEMERIS_HEADER (id), UNIQUE(HEADER_ID, NAME))
CREATE CACHED TABLE ONEAU.OBSERVATION (id INTEGER PRIMARY KEY, FILE_ID INTEGER NOT NULL,MEASURED_ITEM_ID INTEGER NOT NULL, OBSERVATION_NUM INTEGER NOT NULL,INTERVAL_ID INTEGER, COEFFICIENT NUMERIC NOT NULL, FOREIGN KEY(FILE_ID) REFERENCES ONEAU.EPHEMERIS_DATA (id), FOREIGN KEY(MEASURED_ITEM_ID) REFERENCES ONEAU.MEASURED_ITEM (id), FOREIGN KEY (INTERVAL_ID) REFERENCES ONEAU.EPHEMERIS_INTERVAL (id))
